version: '3.8' 
services:
  example.api:
    image: example.api
    build:
      context: .
      dockerfile: Example.Api/Dockerfile
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: "Password!"  
      POSTGRES_USER: postgres
      POSTGRES_DB: orderdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  
volumes:
  postgres_data: {}
